export const benchmarkData = [
    {
        id:1,
        eightCore: 500,
        quadCore: 230,
        increse: "2.1x",
        textInfo: "more Amp Designer plug-ins",
    },
    {
        id:2,
        eightCore: 500,
        quadCore: 230,
        increse: "2.1x",
        textInfo: "faster simulation of dynamical systems",
    },
    {
        id:3,
        eightCore: 500,
        quadCore: 230,
        increse: "2.1x",
        textInfo: "faster Arnold render",
    },
    {
        id:4,
        eightCore: 195,
        quadCore: 100,
        increse: "95%",
        textInfo: "faster render scene to disk",
    },
    {
        id:5,
        eightCore: 185,
        quadCore: 100,
        increse: "85%",
        textInfo: "faster CPU benchmark performance",
    },
    {
        id:6,
        eightCore: 180,
        quadCore: 100,
        increse: "80%",
        textInfo: "faster build time using Xcode",
    },
    {
        id:7,
        eightCore: 165,
        quadCore: 100,
        increse: "65%",
        textInfo: "faster TetrUSS computational fluid dynamics performance",
    },
    {
        id:8,
        eightCore: 160,
        quadCore: 100,
        increse: "70%",
        textInfo: "faster processing of well-threaded filters",
    },
    {
        id:9,
        eightCore: 170,
        quadCore: 100,
        increse: "70%",
        textInfo: "faster RAW image import with Smart Previews",
    },
    {
        id:10,
        eightCore: 170,
        quadCore: 100,
        increse: "60%",
        textInfo: "faster 4K H.264 export",
    },
    {
        id:11,
        eightCore: 160,
        quadCore: 100,
        increse: "55%",
        textInfo: "simultaneous 4K multicam streams",
    },
    {
        id:12,
        eightCore: 150,
        quadCore: 100,
        increse: "11",
        textInfo: "more Amp Designer plug-ins",
    },
];